name 'nginx'
maintainer 'Sean Holden'
maintainer_email 'seanholden1@gmail.com'
license 'all_rights'
description 'Installs/Configures nginx'
long_description 'Installs/Configures nginx'
version '0.1.0'
